### ISSUE TITLE
running in multiple gpu, got `CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasSgemm`

### ISSUE THREAD

**Issue by yzbx** [IDEA-Research/GroundingDINO#67]
# question

- how to use pytorch>=1.8, cuda>=11.0 with multiple gpu at the same time?

# running with single gpu is okay

I run the grounding dino code in docker image.
```
python -m torch.utils.collect_env

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.8.0
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] cudatoolkit-dev           11.1.1           py38h497a2fe_0    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.9.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch
```

# running with multiple gpu got error
```
run 5000 images in 10000 under rank 1
run 5000 images in 10000 under rank 0
filename:   0%|                                                            | 0/5000 [00:00<?, ?it/s]
final text_encoder_type: bert-base-uncased
final text_encoder_type: bert-base-uncased
_IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
_IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
filename:  14%|█████████████████████████████▌                    | 679/5000 [00:13<00:47, 91.21it/s]
/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
filename:  17%|████████████████████████████████████▊            | 844/5000 [00:52<17:17,  4.01it/s]
Traceback (most recent call last):
File "my/detect.py", line 146, in <module>
mp.spawn(main, args=(args,), nprocs=args.world_size, join=True)
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
while not context.join():
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
fn(i, *args)
File "/AI-data/wangjiaxin/GroundingDINO/ymir/detect.py", line 111, in main
logits_filt, boxes_filt, pred_phrases = get_grounding_output(
File "/AI-data/wangjiaxin/GroundingDINO/demo/inference_on_a_image.py", line 93, in get_grounding_output
outputs = model(image[None], captions=[caption])
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/AI-data/wangjiaxin/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 314, in forward
hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/AI-data/wangjiaxin/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 258, in forward
memory, memory_text = self.encoder(
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/AI-data/wangjiaxin/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 576, in forward
output = checkpoint.checkpoint(
File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 177, in checkpoint
return CheckpointFunction.apply(function, preserve, *args)
File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 75, in forward
outputs = run_function(*args)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/AI-data/wangjiaxin/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 785, in forward
src2 = self.self_attn(
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/AI-data/wangjiaxin/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 354, in forward
output = self.output_proj(output)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
return F.linear(input, self.weight, self.bias)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`   
```

# reference
- [use torch1.7 instead of 1.8](https://stackoverflow.com/questions/66567324/pytorch-error-cuda-error-cublas-status-internal-error-when-calling-cublascrea)
```
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch
```

**Comment by HassanBinHaroon** [comment]
Try this easy and quick inference on Google Colab. [GroundingDINO-Inference](https://github.com/HassanBinHaroon/GroundingDINO-Inference)

**Comment by yzbx** [comment]
as we know the error is from `groundingdino/models/GroundingDINO/ms_deform_attn.py`
after search the source of `ms_deform_attn`, I try [Deformable-DETR](https://github.com/fundamentalvision/Deformable-DETR) and [mmcv](https://github.com/open-mmlab/mmcv/blob/main/mmcv/ops/multi_scale_deform_attn.py)

I found the solution in mmcv is simple (Deformable-DETR is depracted), now grounding-dino support multi-gpu inference.

1. install mmcv
2. replace the `_C` in `groundingdino/models/GroundingDINO/ms_deform_attn.py`

```
try:
    # from groundingdino import _C
    from mmcv.utils import ext_loader
    _C = ext_loader.load_ext(
        '_ext', ['ms_deform_attn_backward', 'ms_deform_attn_forward'])

except:
    warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
```
